eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #where our registry server is located

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/auth/users/current
      token-info-uri: http://localhost:8080/auth/oauth/check_token

# Actuator
management:
  metrics:
    export:
    prometheus:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    beans:
      enabled: true
    health:
      show-details=always:
  endpoints:
    web:
      exposure:
        include: "*"

http:
  mappers:
    jsonPrettyPrint=true:
      
