version: '3'
services:
  calory-portal-config:
    container_name: calory-portal-config-1
    image: rdublin/calory/calory-portal-config:0.1.0
    restart: always
    ports:
      - "9888:8888"
    volumes:
      - ./resources/calory-portal-config/shared/:/app/shared
    environment:
      "spring.profiles.active": native
      "spring.cloud.config.server.native.searchLocations": classpath:/shared,file:/app/shared

  calory-portal-registry:
    container_name: calory-portal-registry-1
    image: rdublin/calory/calory-portal-registry:0.1.0
    restart: always
    ports:
      - "9761:8761"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://calory-portal-config:8888
    depends_on:
      - calory-portal-config
  calory-portal-gateway:
    container_name: calory-portal-gateway-1
    image: rdublin/calory/calory-portal-gateway:0.1.0
    restart: always
    ports:
      - "9080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://calory-portal-config:8888
    depends_on:
      - calory-portal-config
      - calory-portal-registry

  calory-portal-auth-mysql:
    container_name: calory-portal-auth-mysql-1
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: calory_portal_auth
      MYSQL_ROOT_PASSWORD: 123456Qw
      MYSQL_ROOT_HOST: '%'
    ports:
      - "9306:3306"
    restart: always
  calory-portal-auth:
    container_name: calory-portal-auth-1
    image: rdublin/calory/calory-portal-auth:0.1.0
    restart: always
    ports:
      - "9082:8082"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://calory-portal-config:8888
    depends_on:
      - calory-portal-config
      - calory-portal-auth-mysql

  calory-portal-calories-mysql:
    container_name: calory-portal-calories-mysql-1
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: calory_portal_calories
      MYSQL_ROOT_PASSWORD: 123456Qw
      MYSQL_ROOT_HOST: '%'
    ports:
      - "9307:3306"
    restart: always
  calory-portal-calories:
    container_name: calory-portal-calories-1
    image: rdublin/calory/calory-portal-calories:0.1.0
    restart: always
    ports:
      - "9084:8084"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://calory-portal-config:8888
    depends_on:
      - calory-portal-config
      - calory-portal-calories-mysql

  calory-portal-ui:
    container_name: calory-portal-ui-1
    image: rdublin/calory/calory-portal-ui:0.1.0
    restart: always
    ports:
      - "9081:8081"
    volumes:
      - ./resources/calory-portal-ui/env.js:/app/resources/env.js
    environment:
      SPRING_CLOUD_CONFIG_URI: http://calory-portal-config:8888
    depends_on:
      - calory-portal-config

